# Site settings
title: NetKet
email: netket@netket.org
description: >
  NetKet is an open-source project delivering cutting-edge methods for the study of many-body quantum systems with artificial neural networks and machine learning techniques. NetKet provides state-of-the-art Neural-Network Quantum states, and advanced learning algorithms to find the ground-state of many-body Hamiltonians. NetKet provides a modular infrastructure for the development and application of machine-learning techniques to many-body quantum systems. You can set up your custom many-body Hamiltonian, observables, lattices, and machines in minutes. The learning algorithms used in NetKet are intrinsically amenable to massive parallelism. NetKet is built using MPI primitives, and can scale up to thousands of CPU cores. Find out our challenges and get involved in the NetKet Project now. Contributing developers will author a paper describing the NetKet library. NetKet is supported by the Simons Foundation and the Flatiron Institute. NetKet's developer lead and founder is Giuseppe Carleo.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.netket.org/ # the base hostname & protocol for your site
git_address: https://github.com/NetKet/netket

twitter:
  username: NetKetOrg

logo:
  /img/logo_small.jpg

latest_release:
  zip: https://github.com/netket/netket/archive/v1.0.1.zip
  gz: https://github.com/netket/netket/archive/v1.0.1.tar.gz

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: flatly

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md

exclude: [vendor] # make sure to exclude 'vendor' from the build

timezone: America/New_York

defaults:
- scope:
    path: _challenges
    type: challenges
  values:
    layout: challenges
    sectionid: challenges

- scope:
    path: _about
    type: about
  values:
    layout: about
    sectionid: about

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _tutorials
    type: tutorials
  values:
    layout: tutorials
    sectionid: tutorials

- scope:
    path: _getstarted
    type: getstarted
  values:
    layout: getstarted
    sectionid: getstarted

collections:
  docs:
    permalink: /:collection/:path/
    output: true

  challenges:
    permalink: /:collection/:path/
    output: true

  about:
    permalink: /:collection/:path/
    output: true

  tutorials:
    permalink: /:collection/:path/
    output: true

  getstarted:
    permalink: /:collection/:path/
    output: true
