# Site settings
title: NetKet
email: netket@netket.org
description: >
  NetKet, open-source library for the development of machine intelligence for many-body quantum systems.

baseurl: "/netket-website" # the subpath of your site, e.g. /blog/
url: https://netket.gitlab.io/ # the base hostname & protocol for your site
git_address: https://netket.gitlab.io/


# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: flatly

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - csl/styles

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md

exclude: [vendor] # make sure to exclude 'vendor' from the build

timezone: America/New_York

defaults:
- scope:
    path: _challenges
    type: challenges
  values:
    layout: challenges
    sectionid: challenges

- scope:
    path: _about
    type: about
  values:
    layout: about
    sectionid: about

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true

  challenges:
    permalink: /:collection/:path/
    output: true

  about:
    permalink: /:collection/:path/
    output: true
